name: Lighthouse Performance Test on Pixel Studios Website

on: [push]

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install Lighthouse
      run: npm install -g lighthouse
      
    - name: Run Lighthouse
      run: lighthouse https://www.pixel-studios.com/ --output json --output-path ./lighthouse-results.json --quiet --chrome-flags="--headless"
      
    - name: Upload Lighthouse Results
      uses: actions/upload-artifact@v2
      with:
        name: Lighthouse Results
        path: ./lighthouse-results.json
